plugins {
    id 'nva.root-module-conventions'
}

nva {
    dependencyAnalysis {
        enforced = true
    }
    spotless {
        enabled = false // FIXME
    }
}

subprojects {
    pluginManager.withPlugin('nva.java-conventions') {
        nva {
            errorprone {
                allErrorsAsWarnings = false
            }
            java {
                languageVersion = 21
            }
            pmd {
                rulesetFile = rootProject.file('config/pmd/ruleset.xml')
            }
            spotless {
                enabled = false // FIXME
            }
        }
        dependencies {
            testRuntimeOnly(nvaCatalog.junit.jupiter.engine)
            testRuntimeOnly(nvaCatalog.junit.platform.launcher)
        }
    }
}
